### ISSUE TITLE
Fatal Crash

### ISSUE THREAD

**Issue by McSkinnerOG** [ConfuzzedCat/TerrariaInjector#2]
[log_2022-11-25-15-43-42.txt](https://github.com/ConfuzzedCat/TerrariaInjector/files/10088981/log_2022-11-25-15-43-42.txt)

Have no idea why this happens as i am not well versed in the language.
Game version is 1.4.4.9 "I'm aware the Tool is for an earlier version"

**Comment by McSkinnerOG** [comment]
Removing the Menu Patch Lets the game load but doesnt seem to pickup mods from the mods folder "I used the example mod and none of the logger stuff showed"
`[HarmonyPatch]
public class MainMenuPatch
{
    public static MethodBase TargetMethod()
    {
        return Program.game.GetType("Terraria.Main").GetMethod("DrawVersionNumber", BindingFlags.NonPublic | BindingFlags.Static);
    }
    public static void Prefix()
    {
        Program.game.GetType("Terraria.Main").GetField("versionNumber").SetValue(null, "v1.4.4.9 - Injected");
    }
}`

**Comment by ConfuzzedCat** [comment]
Sorry, its my bad. I have already fixed this, but forgot to upload the code and new release. 
The issue is that they(Terraria's devs) change the Main class from non-static to static which makes it run its constructor when patching the game, but since that isnt the first thing to happen when game is ran normally it is missing some info, mainly the game save dir. I will upload the code and exe later today

**Comment by ConfuzzedCat** [comment]
new release has been uploaded
